# Generated by Django 5.0.1 on 2024-04-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_order_paid_order_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='User',
            new_name='user',
        ),
    ]
