# Generated by Django 5.0.1 on 2024-04-09 05:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_order_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='order_new',
        ),
    ]
